# Generated by Django 5.1.6 on 2025-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('in_stock', models.IntegerField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('page', models.IntegerField()),
                ('File_format', models.CharField(max_length=128)),
            ],
        ),
    ]
