# Generated by Django 5.1.6 on 2025-03-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_page_book_pages_alter_book_file_format_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='publishDate',
        ),
    ]
