# Generated by Django 5.1.6 on 2025-03-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_publication_date_book_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
